### ISSUE TITLE
Migrate Docker repo-info metadata for skycoin/skycoin repo images

### ISSUE THREAD

**Issue by olemis** [skycoin/repo-info#1]
- [x] Structure similar to [Docker library repo-info store](https://github.com/docker-library/repo-info)
- [x] Same files found in [skycoin/skycoin Docker src folder](https://github.com/skycoin/skycoin/tree/develop/docker).

**Comment by stdevPavelmc** [comment]
What LICENCE we must use for this?

Apache 2.0 / GPL 2.0 - 3.0 ?

**Comment by stdevPavelmc** [comment]
"Structure similar to Docker library repo-info store" 
Done: https://github.com/simelo/skycoin-repo-info/commit/a1fad7a04ea48a5f91f68436b901221d9ea9afa6

Working on "Same files found in skycoin/skycoin Docker src folder."

**Comment by stdevPavelmc** [comment]
"Same files found in skycoin/skycoin Docker src folder."
Done.

**Comment by stdevPavelmc** [comment]
I have a question:

In the docker/repo-info structure they use ONLY ONE folder to host a repository regardless of the tags they use, and here we are using two folders (dev-cli & dev-docker) to represent two repository tags of the same repository "name"

I explain the problem:
We have two independent images (each one has a individual Dockerfile) 
- skycoin/skycoindev-cli:develop
- skycoin/skycoindev-cli:dind

From the image names any user can assume that they are the same image with different tags, when they are two independent images with no related tags.

In the docker-/repo-info repository they use the tags ONLY to differentiate arch/status, but we in this case are using tags not in the same way.

Think about it... it's that correct against the guidelines of docker hub? it's intuitive for the users? 

IMHO we must separate them by NAME noy only by tag, but as I'm the newbie I must ask first.

Cheers. 

(both are named the same, only difference is tag, but they are )
