### ISSUE TITLE
Improve repo-info and docs for Docker dev images

### ISSUE THREAD

**Issue by olemis** [skycoin/repo-info#2]
- [x] [dind image source](https://github.com/skycoin/skycoin/tree/develop/docker/images/dev-docker) is missing repo-info .
- [x] All images are missing labels (see [wikiwi/docker-build image metadata](https://microbadger.com/images/wikiwi/docker-build) for a list of labels)
  *  `org.label-schema.name`
  *  `org.label-schema.vcs-url`
  *  `org.label-schema.vendor`
  *  the rest of [org.label-schema](http://label-schema.org/rc1/) labels.
- [x] Check and automate `repo-info` generation for images generated from (at least) `master` branch
- [x] Mention [dind image](https://github.com/skycoin/skycoin/tree/develop/docker/images/dev-docker) in [development Docker images section](https://github.com/skycoin/skycoin/blob/develop/README.md#development-image) .
- [x] Review docs about Docker images for completeness.
- [x] Structure similar to [Docker library repo-info store](https://github.com/docker-library/repo-info).
- [x] Automate updates in one of two ways:
  * [ **PREFERRED** ] gather new `repo-info` and submit changes in a PR (similar to @snyk-bot vulnerability checker e.g. see [PR skycoin/skycoin-web#449]https://github.com/skycoin/skycoin-web/pull/449) .
  * commit + push changes directly

**Comment by olemis** [comment]
@stdevpavelmc #1 comes first , please , so as to have proper diffs in history.

**Comment by stdevYuniers** [comment]
@stdevPavelmc #3 is done and PR #4 was created. Please check it and tell me if anything must be changed.

**Note:** Repo info under `repos/dev-vscode/remote` is null because docker image in Docker Hub registry is missing.

**Comment by stdevPavelmc** [comment]
Ups!, I saw this after writing here https://github.com/simelo/skycoin-repo-info/pull/4#issuecomment-436998479, so the remote part is empty because there is no image on Docker Hub, is that correct ?

You can fill that info by using a local registry also, pull "library/registry" image and create your own registry, push them into it and (temporary) change the script to point to your local repository, then re-run it and you will have the data in place.

If you need more info on how to do that make a google search about running/using a local docker registry.

Cheers.

**Comment by stdevPavelmc** [comment]
All images are missing labels (see wikiwi/docker-build image metadata for a list of labels) 

This is addressed on https://github.com/skycoin/skycoin/pull/1997 as the LABELS are incorporated on the Dockerfile and buil of the docker images, no on this repo.

**Comment by stdevPavelmc** [comment]
Mention dind image in development Docker images 

Is addressed on https://github.com/skycoin/skycoin/pull/1997

**Comment by stdevPavelmc** [comment]
Automate updates in one of two ways...

For now commit + PR
