### ISSUE TITLE
[docker] Add metadata for VS Code image

### ISSUE THREAD

**Issue by stdevYuniers** [skycoin/repo-info#3]
Is necessary add vscode images into this repo in order to generate all repo-info metadata of Skycoin docker images.

**Comment by stdevPavelmc** [comment]
Please check that 
https://github.com/simelo/skycoin-repo-info/commit/b3f87eb7ee4767704f4cb0e3c078186aae399ea3#diff-1e80975be11c7d16346aafe12fd36184 
and 
https://github.com/simelo/skycoin-repo-info/commit/b3f87eb7ee4767704f4cb0e3c078186aae399ea3#diff-c41b302b787467ce3c3243e170f31fcf 
are both empty...

**Comment by stdevYuniers** [comment]
@stdevPavelmc Sorry for delay.

> Please check that the remote part of both images are empty, no relevant content in there.

On 4b8a212 it was fixed. VS Code docker images are published on Docker Hub and generate repo info for it is more easy now.
